import panda
panda1=panda.Panda("white","panda1",1.4,16)
panda2=panda.Panda("white","panda2",1.8,17)
panda3=panda.Panda("white and black","panda3",1.7,12)
panda4=panda.Panda("black","panda4",1.3,10)
print(panda1.age)
panda1.sleep()
panda1.play()
panda2.sleep()
panda2.play()
panda3.sleep()
panda3.play()
panda4.sleep()
panda4.play()